### PR TITLE
Update segwit reading list and questions sort order

### PR DESCRIPTION
**Pull request by jonatack**
The reading list and questions seem to be somewhat out of order--made a guess as to the desired order, happy to adjust per feedback.

(Should the "SegWit Wallet Development" reading be labeled as optional? The question relating to it is indicated as optional.)

### CODE REVIEW

**Comment by jonatack** [comment]
(I'm also not sure if there is a reading missing for the question pertaining to "Gregory Maxwell’s Inhibition Proposal" or if I just haven't made a connection to it yet from the current reading list that I'm only part of the way through so far.)

**Comment by adamjonas** [comment]
Indeed, we were missing [Gregory Maxwell’s Inhibition Proposal](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-April/013996.html).

**Review by Xekyo — APPROVED** [review]

**Comment by Xekyo** [comment]
Note to self: I realized that the master branch is out of sync with the gitbook, and that's why this isn't merged yet.

**Comment by adamjonas** [comment]
Tried to capture of the spirit of this in 6c38b84 of #66.

**Comment by Xekyo** [comment]
I see, yeah that should cover it.

**Pull request closed without merging**
