### PR TITLE
add blinded routing

### PR DESCRIPTION
**Pull request by adamjonas**
cc @carlakc & @Xekyo

### CODE REVIEW

**Comment by Xekyo** [comment]
I thought it sounded like we might want to drop Rendezvous Routing altogether. Did I misunderstand what you were saying, @carlakc?

**Comment by adamjonas** [comment]
Rendezvous is referenced in the doc. Guidance @carlakc?

**Comment by adamjonas** [comment]
Rendezvous is referenced in the doc so removing might lead to additional confusion.

**Comment by carlaKC** [comment]
> I thought it sounded like we might want to drop Rendezvous Routing altogether. Did I misunderstand what you were saying, @carlaKC?

afaik it seems to be the preferred solution at the moment, but since nothing is decided on yet I think it would make sense to leave both so that they can be compared?

**Comment by adamjonas** [comment]
Good enough for me. Merging.

**Pull request merged**
